DEFAULT: &DEFAULT
  use_gpu: True  # todo
  gpu_ids: [4]
  num_gpus_total: 5
  num_gpus_to_use: 1
  model_debug: False
  dataset_debug: False
  dataset_seed: 42
  model_seed: 42
  verbose: 1
  save_model: True
  val_interval: 1
  data_sampler_num_workers: 5  # todo
  precision: 16
  accumulate_grad_batches: 16  # todo
  use_pruner: False

  lr: 0.001
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 75
  use_skip: True


FNTN: &FNTN
  <<: *DEFAULT
  dataset_id: "0.0"
  dataset_slice_type: num_edges
  num_classes: 4
  global_channels: 32
  global_channel_type: Embedding
  obs_max_len: 20
  log_dir: ../lightning_logs_fntn/

SGI-FNTN-TEST:
  <<: *FNTN
  save_model: True
  model_debug: False
  dataset_debug: True
  lambda_aux_x: 1.0
  lambda_aux_e: 1.0
  epochs: 2

SGI-FNTN-BASE: &SGI-FNTN-BASE
  <<: *FNTN
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

SGI-FNTN-Linear: &SGI-FNTN-Linear
  <<: *SGI-FNTN-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

SGI-FNTN-Linear-SHORT: &SGI-FNTN-Linear-SHORT
  <<: *SGI-FNTN-Linear
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

SGI-FNTN-Linear-SHORT-PGA:
  <<: *SGI-FNTN-Linear-SHORT
  use_pergraph_attr: True
  lambda_l2: 4.5200e-7

SGI-FNTN-Linear-TRAIN-MAX-EVAL-SHORT: &SGI-FNTN-Linear-TRAIN-MAX-EVAL-SHORT
  <<: *SGI-FNTN-Linear
  train_dataset_slice_range_1: 3089
  train_dataset_slice_range_2: 3090
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

SGI-FNTN-Linear-TRAIN-MAX-EVAL-SHORT-PGA:
  <<: *SGI-FNTN-Linear-TRAIN-MAX-EVAL-SHORT
  use_pergraph_attr: True
  lambda_l2: 1.6697e-7

SGI-FNTN-BISAGE: &SGI-FNTN-BISAGE
  <<: *SGI-FNTN-BASE
  gnn_name: SAGEConv
  is_bidirectional: True
  readout_name: mean
  lambda_l2: 1e-3

SGI-FNTN-BIGCN-SHORT: &SGI-FNTN-BIGCN-SHORT
  <<: *SGI-FNTN-BISAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10
  lambda_l2: 0.00043154

SGI-FNTN-BISAGE-SHORT: &SGI-FNTN-BISAGE-SHORT
  <<: *SGI-FNTN-BISAGE
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

SGI-FNTN-BISAGE-LONG: &SGI-FNTN-BISAGE-LONG
  <<: *SGI-FNTN-BISAGE
  dataset_slice_range_1: 100
  dataset_slice_range_2: 105

SGI-FNTN-BISAGE-XLONG: &SGI-FNTN-BISAGE-XLONG
  <<: *SGI-FNTN-BISAGE
  dataset_slice_range_1: 200
  dataset_slice_range_2: 205

SGI-FNTN-BISAGE-25P: &SGI-FNTN-BISAGE-25P
  <<: *SGI-FNTN-BISAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2

SGI-FNTN-BISAGE-50P: &SGI-FNTN-BISAGE-50P
  <<: *SGI-FNTN-BISAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2

SGI-FNTN-BISAGE-MAX: &SGI-FNTN-BISAGE-MAX
  <<: *SGI-FNTN-BISAGE
  dataset_slice_range_1: 3089
  dataset_slice_range_2: 3090

SGI-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT: &SGI-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT
  <<: *SGI-FNTN-BISAGE
  train_dataset_slice_range_1: 3089
  train_dataset_slice_range_2: 3090
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

SGI-FNTN-BISAGE-SHORT-0SG: &SGI-FNTN-BISAGE-SHORT-0SG
  <<: *SGI-FNTN-BISAGE-SHORT
  data_use_obs_edge_only: False

SGI-FNTN-BISAGE-LONG-0SG: &SGI-FNTN-BISAGE-LONG-0SG
  <<: *SGI-FNTN-BISAGE-LONG
  data_use_obs_edge_only: False

SGI-FNTN-BISAGE-XLONG-0SG: &SGI-FNTN-BISAGE-XLONG-0SG
  <<: *SGI-FNTN-BISAGE-XLONG
  data_use_obs_edge_only: False

SGI-FNTN-BISAGE-MAX-0SG: &SGI-FNTN-BISAGE-MAX-0SG
  <<: *SGI-FNTN-BISAGE-MAX
  data_use_obs_edge_only: False

SGI-FNTN-BISAGE-SHORT-1SG: &SGI-FNTN-BISAGE-SHORT-1SG
  <<: *SGI-FNTN-BISAGE-SHORT
  data_use_obs_edge_only: False
  data_sampler_num_hops: 1

SGI-FNTN-BIGCN-SHORT-PGA:
  <<: *SGI-FNTN-BIGCN-SHORT
  use_pergraph_attr: True

SGI-FNTN-BISAGE-SHORT-PGA:
  <<: *SGI-FNTN-BISAGE-SHORT
  use_pergraph_attr: True
  lambda_l2: 0.00028476

SGI-FNTN-BISAGE-LONG-PGA:
  <<: *SGI-FNTN-BISAGE-LONG
  use_pergraph_attr: True
  lambda_l2: 0.00023504

SGI-FNTN-BISAGE-25P-PGA:
  <<: *SGI-FNTN-BISAGE-25P
  use_pergraph_attr: True
  lambda_l2: 0.00026687

SGI-FNTN-BISAGE-50P-PGA:
  <<: *SGI-FNTN-BISAGE-50P
  use_pergraph_attr: True
  lambda_l2: 0.00026903

SGI-FNTN-BISAGE-XLONG-PGA:
  <<: *SGI-FNTN-BISAGE-XLONG
  use_pergraph_attr: True
  lambda_l2: 0.00018054

SGI-FNTN-BISAGE-MAX-PGA:
  <<: *SGI-FNTN-BISAGE-MAX
  use_pergraph_attr: True
  lambda_l2: 0.00022044

SGI-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT-PGA:
  <<: *SGI-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT
  use_pergraph_attr: True
  lambda_l2: 0.00031851

SGI-FNTN-BISAGE-SHORT-0SG-PGA:
  <<: *SGI-FNTN-BISAGE-SHORT-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000010522

SGI-FNTN-BISAGE-LONG-0SG-PGA:
  <<: *SGI-FNTN-BISAGE-LONG-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000043985

SGI-FNTN-BISAGE-XLONG-0SG-PGA:
  <<: *SGI-FNTN-BISAGE-XLONG-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000027055

SGI-FNTN-BISAGE-MAX-0SG-PGA:
  <<: *SGI-FNTN-BISAGE-MAX-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000056615

SGI-FNTN-BISAGE-SHORT-1SG-PGA:
  <<: *SGI-FNTN-BISAGE-SHORT-1SG
  use_pergraph_attr: True
  lambda_l2: 0.000347723

SGI-FNTN-SHORT-ISI-X-GB-PGA:
  <<: *SGI-FNTN-BASE
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10
  gnn_name: SAGEConv
  is_bidirectional: True
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  use_inter_subgraph_infomax: True
  use_pergraph_attr: True
  lambda_aux_x: 0.0
  readout_name: mean
  lambda_l2: 0.00018279
  lambda_aux_isi: 2.00
  m: fntn-inter-3

SGI-FNTN-BIE2D2F64: &SGI-FNTN-BIE2D2F64
  <<: *FNTN
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10
  gnn_name: SAGEConv
  use_decoder: True
  is_bidirectional: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.5
  num_encoder_layers: 2
  num_decoder_body_layers: 2

SGI-FNTN-BIE2D2F64-X: &SGI-FNTN-BIE2D2F64-X  # not-used
  <<: *SGI-FNTN-BIE2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

SGI-FNTN-BIE2D2F64-X-PGA:
  <<: *SGI-FNTN-BIE2D2F64-X
  use_pergraph_attr: True
  lambda_aux_isi: 0.0
  lambda_l2: 0.00024979
  lambda_aux_x: 2.49
  data_sampler_dropout_edges: 0.55
  pool_ratio: 0.0016009

SGI-FNTN-BIE2D2F64-E:  # not-used
  <<: *SGI-FNTN-BIE2D2F64
  main_decoder_type: edge
  use_node_decoder: False
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_e: 0.5
  pool_ratio: 0.2

SGI-FNTN-BIE2D2F64-XE:  # not-used
  <<: *SGI-FNTN-BIE2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_x: 0.05
  lambda_aux_e: 0.1
  pool_ratio: 0.1

SGI-FNTN-BIE2D2F64-EX:  # not-used
  <<: *SGI-FNTN-BIE2D2F64
  main_decoder_type: edge
  use_node_decoder: True
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_e: 0.25
  pool_ratio: 0.1


SGI-FNTN-BIE2D2F64-ISI: &SGI-FNTN-BIE2D2F64-ISI
  <<: *SGI-FNTN-BIE2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.3

SGI-FNTN-BIE2D2F64-ISI-X: &SGI-FNTN-BIE2D2F64-ISI-X
  <<: *SGI-FNTN-BIE2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

SGI-FNTN-BIE2D2F64-ISI-X-GB:  # not-used
  <<: *SGI-FNTN-BIE2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.1

SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA: &SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA
  <<: *SGI-FNTN-BIE2D2F64-ISI-X
  use_pergraph_attr: True
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 0.0018817
  lambda_aux_x: 5.80
  lambda_aux_isi: 1.85
  data_sampler_dropout_edges: 0.60
  pool_ratio: 0.010994

SGI-FNTN-BIE2D2F64-ISI-X-SG-PGA: &SGI-FNTN-BIE2D2F64-ISI-X-SG-PGA
  <<: *SGI-FNTN-BIE2D2F64-ISI-X
  use_pergraph_attr: True
  inter_subgraph_infomax_edge_type: subgraph
  lambda_l2: 0.0010923
  lambda_aux_x: 0.02
  lambda_aux_isi: 3.36
  data_sampler_dropout_edges: 0.50
  pool_ratio: 0.037004

SGI-FNTN-BIE2D2F64-ISI-X-SG-PGA-08:
  <<: *SGI-FNTN-BIE2D2F64-ISI-X-SG-PGA
  data_sampler_dropout_edges: 0.50
  lambda_l2: 0.001
  lambda_aux_x: 2.0
  lambda_aux_isi: 3.0
  pool_ratio: 0.001

SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA-08:
  <<: *SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA
  log_dir: ../lightning_logs_fntn_grid_report/
  data_sampler_dropout_edges: 0.50
  lambda_l2: 0.001
  lambda_aux_x: 1.0
  lambda_aux_isi: 3.0
  pool_ratio: 0.01
  m: fntn-08-v1

SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA-16:
  <<: *SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA
  log_dir: ../lightning_logs_fntn_grid_report/
  dataset_slice_range_1: 13
  dataset_slice_range_2: 18
  obs_max_len: 36
  data_sampler_dropout_edges: 0.50
  lambda_l2: 0.001
  lambda_aux_x: 2.0
  lambda_aux_isi: 1.0
  pool_ratio: 0.01
  m: fntn-16-v2

SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA-32:
  <<: *SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA
  log_dir: ../lightning_logs_fntn_grid_report/
  dataset_slice_range_1: 29
  dataset_slice_range_2: 34
  obs_max_len: 68
  data_sampler_dropout_edges: 0.50
  lambda_l2: 0.001
  lambda_aux_x: 1.0
  lambda_aux_isi: 2.0
  pool_ratio: 0.01
  m: fntn-32-v2

SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA-64:
  <<: *SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA
  log_dir: ../lightning_logs_fntn_grid_report/
  dataset_slice_range_1: 61
  dataset_slice_range_2: 66
  obs_max_len: 132
  data_sampler_dropout_edges: 0.50
  lambda_l2: 0.001
  lambda_aux_x: 2.0
  lambda_aux_isi: 2.0
  pool_ratio: 0.001
  m: fntn-real-64-v2


HPOMetab: &HPOMetab
  <<: *DEFAULT
  dataset_id: HPOMetab
  dataset_slice_type: random
  num_classes: 6
  global_channels: 64
  global_channel_type: Pretrained
  include_obs_x_in_pooling: True
  is_obs_sequential: False
  lr: 0.001

  batch_size: 4
  eval_batch_size: 3
  accumulate_grad_batches: 16
  data_sampler_num_workers: 40
  epochs: 200
  val_interval: 1
  log_dir: ../lightning_logs_metab/


SGI-HPOMetab-BASE: &SGI-HPOMetab-BASE
  <<: *HPOMetab
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

SGI-HPOMetab-Linear: &SGI-HPOMetab-Linear
  <<: *SGI-HPOMetab-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

SGI-HPOMetab-Linear-SHORT: &SGI-HPOMetab-Linear-SHORT
  <<: *SGI-HPOMetab-Linear
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000055036

SGI-HPOMetab-Linear-TRAIN-MAX-EVAL-SHORT: &SGI-HPOMetab-Linear-TRAIN-MAX-EVAL-SHORT
  <<: *SGI-HPOMetab-Linear
  train_dataset_slice_range_1: 50
  train_dataset_slice_range_2: 51
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.0000031107


SGI-HPOMetab-SAGE: &SGI-HPOMetab-SAGE
  <<: *SGI-HPOMetab-BASE
  gnn_name: SAGEConv
  readout_name: mean
  lambda_l2: 1e-3

SGI-HPOMetab-GCN-SHORT:
  <<: *SGI-HPOMetab-SAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.00044598

SGI-HPOMetab-SAGE-SHORT: &SGI-HPOMetab-SAGE-SHORT
  <<: *SGI-HPOMetab-SAGE
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000028790

SGI-HPOMetab-SAGE-25P: &SGI-HPOMetab-SAGE-25P
  <<: *SGI-HPOMetab-SAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2
  lambda_l2: 0.00039314

SGI-HPOMetab-SAGE-50P: &SGI-HPOMetab-SAGE-50P
  <<: *SGI-HPOMetab-SAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2
  lambda_l2: 0.00048598

SGI-HPOMetab-SAGE-MAX: &SGI-HPOMetab-SAGE-MAX
  <<: *SGI-HPOMetab-SAGE
  dataset_slice_range_1: 50
  dataset_slice_range_2: 51
  lambda_l2: 0.0000017804

SGI-HPOMetab-SAGE-TRAIN-MAX-EVAL-SHORT:
  <<: *SGI-HPOMetab-SAGE
  train_dataset_slice_range_1: 50
  train_dataset_slice_range_2: 51
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000019960

SGI-HPOMetab-SHORT-ISI-X-GB: &SGI-HPOMetab-SHORT-ISI-X-GB
  <<: *SGI-HPOMetab-BASE
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  gnn_name: SAGEConv
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  use_inter_subgraph_infomax: True
  lambda_aux_x: 0.0
  readout_name: mean
  epochs: 300
  lambda_l2: 0.0000038420
  lambda_aux_isi: 2.9300
  m: metab-inter-1

SGI-HPOMetab-E2D2F64: &SGI-HPOMetab-E2D2F64
  <<: *HPOMetab
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  gnn_name: SAGEConv
  use_decoder: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.95
  data_sampler_no_drop_pos_edges: False
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 300  # todo

SGI-HPOMetab-E2D2F64-X:
  <<: *SGI-HPOMetab-E2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

SGI-HPOMetab-E2D2F64-ISI: &SGI-HPOMetab-E2D2F64-ISI
  <<: *SGI-HPOMetab-E2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.5
  data_sampler_no_drop_pos_edges: False

SGI-HPOMetab-E2D2F64-ISI-X: &SGI-HPOMetab-E2D2F64-ISI-X
  <<: *SGI-HPOMetab-E2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

SGI-HPOMetab-E2D2F64-ISI-X-GB:
  <<: *SGI-HPOMetab-E2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.01


EMUser: &EMUser
  <<: *DEFAULT
  dataset_id: EMUser
  dataset_slice_type: random
  num_classes: 2
  global_channels: 64
  global_channel_type: Pretrained
  is_obs_sequential: False
  include_obs_x_in_pooling: True
  lr: 0.001

  batch_size: 64
  eval_batch_size: 3
  accumulate_grad_batches: 1
  data_sampler_num_workers: 20
  epochs: 200
  val_interval: 1
  log_dir: ../lightning_logs_emuser/


SGI-EMUser-BASE: &SGI-EMUser-BASE
  <<: *EMUser
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

SGI-EMUser-Linear: &SGI-EMUser-Linear
  <<: *SGI-EMUser-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

SGI-EMUser-Linear-SHORT: &SGI-EMUser-Linear-SHORT
  <<: *SGI-EMUser-Linear
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  lambda_l2: 0.0000014086

SGI-EMUser-Linear-TRAIN-MAX-EVAL-SHORT: &SGI-EMUser-Linear-TRAIN-MAX-EVAL-SHORT
  <<: *SGI-EMUser-Linear
  train_dataset_slice_range_1: 499
  train_dataset_slice_range_2: 500
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  lambda_l2: 0.00010494


SGI-EMUser-SAGE: &SGI-EMUser-SAGE
  <<: *SGI-EMUser-BASE
  gnn_name: SAGEConv
  readout_name: mean
  lambda_l2: 1e-3

SGI-EMUser-GCN-SHORT:
  <<: *SGI-EMUser-SAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11

SGI-EMUser-SAGE-SHORT: &SGI-EMUser-SAGE-SHORT
  <<: *SGI-EMUser-SAGE
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  lambda_l2: 0.00019239

SGI-EMUser-SAGE-25P: &SGI-EMUser-SAGE-25P
  <<: *SGI-EMUser-SAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2
  lambda_l2: 0.00023945

SGI-EMUser-SAGE-50P: &SGI-EMUser-SAGE-50P
  <<: *SGI-EMUser-SAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2
  lambda_l2: 0.0000070983

SGI-EMUser-SAGE-MAX: &SGI-EMUser-SAGE-MAX
  <<: *SGI-EMUser-SAGE
  dataset_slice_range_1: 499
  dataset_slice_range_2: 500
  lambda_l2: 0.000039415

SGI-EMUser-SAGE-TRAIN-MAX-EVAL-SHORT:
  <<: *SGI-EMUser-SAGE
  train_dataset_slice_range_1: 499
  train_dataset_slice_range_2: 500
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  lambda_l2: 0.00024352

SGI-EMUser-SHORT-ISI-X-GB: &SGI-EMUser-SHORT-ISI-X-GB
  <<: *SGI-EMUser-BASE
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  gnn_name: SAGEConv
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  use_inter_subgraph_infomax: True
  lambda_aux_x: 0.0
  readout_name: mean
  epochs: 400
  lambda_l2: 2.3018e-7
  lambda_aux_isi: 1.3400
  m: emuser-inter-2

SGI-EMUser-E2D2F64: &SGI-EMUser-E2D2F64
  <<: *EMUser
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  gnn_name: SAGEConv
  use_decoder: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.5
  data_sampler_no_drop_pos_edges: False  # todo
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 400

SGI-EMUser-E2D2F64-X:
  <<: *SGI-EMUser-E2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_aux_isi: 0.0
  lambda_l2: 0.00018086
  lambda_aux_x: 1.00
  data_sampler_dropout_edges: 0.6
  pool_ratio: 0.0036169

SGI-EMUser-E2D2F64-ISI: &SGI-EMUser-E2D2F64-ISI
  <<: *SGI-EMUser-E2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.5
  data_sampler_no_drop_pos_edges: False  # todo

SGI-EMUser-E2D2F64-ISI-X: &SGI-EMUser-E2D2F64-ISI-X
  <<: *SGI-EMUser-E2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  epochs: 600

SGI-EMUser-E2D2F64-ISI-X-GB: &SGI-EMUser-E2D2F64-ISI-X-GB
  <<: *SGI-EMUser-E2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 0.00019286991968807735
  lambda_aux_x: 0.43
  lambda_aux_isi: 0.55
  data_sampler_dropout_edges: 0.45
  pool_ratio: 0.0174784981734352

SGI-EMUser-E2D2F64-ISI-X-GB-08:
  <<: *SGI-EMUser-E2D2F64-ISI-X-GB
  log_dir: ../lightning_logs_emuser_grid_report/
  data_sampler_dropout_edges: 0.50
  lambda_l2: 0.00001
  lambda_aux_x: 1.0
  lambda_aux_isi: 1.0
  pool_ratio: 0.01
  m: emuser-08-v2

SGI-EMUser-E2D2F64-ISI-X-GB-16:
  <<: *SGI-EMUser-E2D2F64-ISI-X-GB
  log_dir: ../lightning_logs_emuser_grid_report/
  dataset_slice_range_1: 14
  dataset_slice_range_2: 19
  data_sampler_dropout_edges: 0.50
  lambda_l2: 0.00001
  lambda_aux_x: 3.0
  lambda_aux_isi: 1.0
  pool_ratio: 0.001
  m: emuser-16-v1

SGI-EMUser-E2D2F64-ISI-X-GB-32:
  <<: *SGI-EMUser-E2D2F64-ISI-X-GB
  log_dir: ../lightning_logs_emuser_grid_report/
  batch_size: 16
  eval_batch_size: 2
  accumulate_grad_batches: 4
  dataset_slice_range_1: 30
  dataset_slice_range_2: 35
  data_sampler_dropout_edges: 0.50
  lambda_l2: 0.00001
  lambda_aux_x: 2.0
  lambda_aux_isi: 1.0
  pool_ratio: 0.001
  m: emuser-32-v1

SGI-EMUser-E2D2F64-ISI-X-GB-64:
  <<: *SGI-EMUser-E2D2F64-ISI-X-GB
  log_dir: ../lightning_logs_emuser_grid_report/
  data_sampler_num_workers: 40
  batch_size: 8
  eval_batch_size: 2
  accumulate_grad_batches: 8
  dataset_slice_range_1: 62
  dataset_slice_range_2: 67
  data_sampler_dropout_edges: 0.50
  lambda_l2: 0.00001
  lambda_aux_x: 1.0
  lambda_aux_isi: 1.0
  pool_ratio: 0.001
  m: emuser-64-v1
