DEFAULT: &DEFAULT
  use_gpu: True  # todo
  gpu_ids: [3]
  num_gpus_total: 4
  num_gpus_to_use: 1
  model_debug: False
  dataset_debug: False
  dataset_seed: 42
  model_seed: 42
  verbose: 1
  save_model: True
  val_interval: 1
  data_sampler_num_workers: 5  # todo
  precision: 16
  accumulate_grad_batches: 16  # todo
  use_pruner: False

  lr: 0.001
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 75
  use_skip: True


FNTN: &FNTN
  <<: *DEFAULT
  dataset_id: "0.0"
  dataset_slice_type: num_edges
  num_classes: 4
  global_channels: 32
  global_channel_type: Embedding
  obs_max_len: 20
  log_dir: ../lightning_logs_fntn/

SGI-FNTN-TEST:
  <<: *FNTN
  save_model: True
  model_debug: False
  dataset_debug: True
  lambda_aux_x: 1.0
  lambda_aux_e: 1.0
  epochs: 2

SGI-FNTN-BASE: &SGI-FNTN-BASE
  <<: *FNTN
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

SGI-FNTN-Linear: &SGI-FNTN-Linear
  <<: *SGI-FNTN-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

SGI-FNTN-Linear-SHORT: &SGI-FNTN-Linear-SHORT
  <<: *SGI-FNTN-Linear
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

SGI-FNTN-Linear-SHORT-PGA:
  <<: *SGI-FNTN-Linear-SHORT
  use_pergraph_attr: True
  lambda_l2: 4.5200e-7

SGI-FNTN-Linear-TRAIN-MAX-EVAL-SHORT: &SGI-FNTN-Linear-TRAIN-MAX-EVAL-SHORT
  <<: *SGI-FNTN-Linear
  train_dataset_slice_range_1: 3089
  train_dataset_slice_range_2: 3090
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

SGI-FNTN-Linear-TRAIN-MAX-EVAL-SHORT-PGA:
  <<: *SGI-FNTN-Linear-TRAIN-MAX-EVAL-SHORT
  use_pergraph_attr: True
  lambda_l2: 1.6697e-7

SGI-FNTN-BISAGE: &SGI-FNTN-BISAGE
  <<: *SGI-FNTN-BASE
  gnn_name: SAGEConv
  is_bidirectional: True
  readout_name: mean
  lambda_l2: 1e-3

SGI-FNTN-BIGCN-SHORT: &SGI-FNTN-BIGCN-SHORT
  <<: *SGI-FNTN-BISAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10
  lambda_l2: 0.00043154

SGI-FNTN-BISAGE-SHORT: &SGI-FNTN-BISAGE-SHORT
  <<: *SGI-FNTN-BISAGE
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

SGI-FNTN-BISAGE-LONG: &SGI-FNTN-BISAGE-LONG
  <<: *SGI-FNTN-BISAGE
  dataset_slice_range_1: 100
  dataset_slice_range_2: 105

SGI-FNTN-BISAGE-XLONG: &SGI-FNTN-BISAGE-XLONG
  <<: *SGI-FNTN-BISAGE
  dataset_slice_range_1: 200
  dataset_slice_range_2: 205

SGI-FNTN-BISAGE-25P: &SGI-FNTN-BISAGE-25P
  <<: *SGI-FNTN-BISAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2

SGI-FNTN-BISAGE-50P: &SGI-FNTN-BISAGE-50P
  <<: *SGI-FNTN-BISAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2

SGI-FNTN-BISAGE-MAX: &SGI-FNTN-BISAGE-MAX
  <<: *SGI-FNTN-BISAGE
  dataset_slice_range_1: 3089
  dataset_slice_range_2: 3090

SGI-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT: &SGI-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT
  <<: *SGI-FNTN-BISAGE
  train_dataset_slice_range_1: 3089
  train_dataset_slice_range_2: 3090
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

SGI-FNTN-BISAGE-SHORT-0SG: &SGI-FNTN-BISAGE-SHORT-0SG
  <<: *SGI-FNTN-BISAGE-SHORT
  data_use_obs_edge_only: False

SGI-FNTN-BISAGE-LONG-0SG: &SGI-FNTN-BISAGE-LONG-0SG
  <<: *SGI-FNTN-BISAGE-LONG
  data_use_obs_edge_only: False

SGI-FNTN-BISAGE-XLONG-0SG: &SGI-FNTN-BISAGE-XLONG-0SG
  <<: *SGI-FNTN-BISAGE-XLONG
  data_use_obs_edge_only: False

SGI-FNTN-BISAGE-MAX-0SG: &SGI-FNTN-BISAGE-MAX-0SG
  <<: *SGI-FNTN-BISAGE-MAX
  data_use_obs_edge_only: False

SGI-FNTN-BISAGE-SHORT-1SG: &SGI-FNTN-BISAGE-SHORT-1SG
  <<: *SGI-FNTN-BISAGE-SHORT
  data_use_obs_edge_only: False
  data_sampler_num_hops: 1

SGI-FNTN-BIGCN-SHORT-PGA:
  <<: *SGI-FNTN-BIGCN-SHORT
  use_pergraph_attr: True

SGI-FNTN-BISAGE-SHORT-PGA:
  <<: *SGI-FNTN-BISAGE-SHORT
  use_pergraph_attr: True
  lambda_l2: 0.00028476

SGI-FNTN-BISAGE-LONG-PGA:
  <<: *SGI-FNTN-BISAGE-LONG
  use_pergraph_attr: True
  lambda_l2: 0.00023504

SGI-FNTN-BISAGE-25P-PGA:
  <<: *SGI-FNTN-BISAGE-25P
  use_pergraph_attr: True
  lambda_l2: 0.00026687

SGI-FNTN-BISAGE-50P-PGA:
  <<: *SGI-FNTN-BISAGE-50P
  use_pergraph_attr: True
  lambda_l2: 0.00026903

SGI-FNTN-BISAGE-XLONG-PGA:
  <<: *SGI-FNTN-BISAGE-XLONG
  use_pergraph_attr: True
  lambda_l2: 0.00018054

SGI-FNTN-BISAGE-MAX-PGA:
  <<: *SGI-FNTN-BISAGE-MAX
  use_pergraph_attr: True
  lambda_l2: 0.00022044

SGI-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT-PGA:
  <<: *SGI-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT
  use_pergraph_attr: True
  lambda_l2: 0.00031851

SGI-FNTN-BISAGE-SHORT-0SG-PGA:
  <<: *SGI-FNTN-BISAGE-SHORT-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000010522

SGI-FNTN-BISAGE-LONG-0SG-PGA:
  <<: *SGI-FNTN-BISAGE-LONG-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000043985

SGI-FNTN-BISAGE-XLONG-0SG-PGA:
  <<: *SGI-FNTN-BISAGE-XLONG-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000027055

SGI-FNTN-BISAGE-MAX-0SG-PGA:
  <<: *SGI-FNTN-BISAGE-MAX-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000056615

SGI-FNTN-BISAGE-SHORT-1SG-PGA:
  <<: *SGI-FNTN-BISAGE-SHORT-1SG
  use_pergraph_attr: True
  lambda_l2: 0.000347723


SGI-FNTN-BIE2D2F64: &SGI-FNTN-BIE2D2F64
  <<: *FNTN
  gnn_name: SAGEConv
  use_decoder: True
  is_bidirectional: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.5
  num_encoder_layers: 2
  num_decoder_body_layers: 2

SGI-FNTN-BIE2D2F64-X: &SGI-FNTN-BIE2D2F64-X  # not-used
  <<: *SGI-FNTN-BIE2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

SGI-FNTN-BIE2D2F64-X-PGA:
  <<: *SGI-FNTN-BIE2D2F64-X
  use_pergraph_attr: True
  lambda_aux_isi: 0.0
  lambda_l2: 0.00024979
  lambda_aux_x: 2.49
  data_sampler_dropout_edges: 0.55
  pool_ratio: 0.0016009

SGI-FNTN-BIE2D2F64-E:  # not-used
  <<: *SGI-FNTN-BIE2D2F64
  main_decoder_type: edge
  use_node_decoder: False
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_e: 0.5
  pool_ratio: 0.2

SGI-FNTN-BIE2D2F64-XE:  # not-used
  <<: *SGI-FNTN-BIE2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_x: 0.05
  lambda_aux_e: 0.1
  pool_ratio: 0.1

SGI-FNTN-BIE2D2F64-EX:  # not-used
  <<: *SGI-FNTN-BIE2D2F64
  main_decoder_type: edge
  use_node_decoder: True
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_e: 0.25
  pool_ratio: 0.1


SGI-FNTN-BIE2D2F64-ISI: &SGI-FNTN-BIE2D2F64-ISI
  <<: *SGI-FNTN-BIE2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.3

SGI-FNTN-BIE2D2F64-ISI-X: &SGI-FNTN-BIE2D2F64-ISI-X
  <<: *SGI-FNTN-BIE2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

SGI-FNTN-BIE2D2F64-ISI-X-GB:  # not-used
  <<: *SGI-FNTN-BIE2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.1

SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA: &SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA
  <<: *SGI-FNTN-BIE2D2F64-ISI-X
  use_pergraph_attr: True
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 0.0018817
  lambda_aux_x: 5.80
  lambda_aux_isi: 1.85
  data_sampler_dropout_edges: 0.60
  pool_ratio: 0.010994

SGI-FNTN-BIE2D2F64-ISI-X-SG-PGA:
  <<: *SGI-FNTN-BIE2D2F64-ISI-X
  use_pergraph_attr: True
  inter_subgraph_infomax_edge_type: subgraph
  lambda_l2: 0.0014368
  lambda_aux_x: 3.73
  lambda_aux_isi: 3.36
  data_sampler_dropout_edges: 0.50
  pool_ratio: 0.083167

SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA-08:
  <<: *SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA
  data_sampler_dropout_edges: 0.50

SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA-16:
  <<: *SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA
  dataset_slice_range_1: 13
  dataset_slice_range_2: 18
  obs_max_len: 36
  data_sampler_dropout_edges: 0.50

SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA-32:
  <<: *SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA
  dataset_slice_range_1: 29
  dataset_slice_range_2: 34
  obs_max_len: 68
  data_sampler_dropout_edges: 0.50

SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA-64:
  <<: *SGI-FNTN-BIE2D2F64-ISI-X-GB-PGA
  dataset_slice_range_1: 61
  dataset_slice_range_2: 66
  obs_max_len: 132
  data_sampler_dropout_edges: 0.50



HPONeuro: &HPONeuro
  <<: *DEFAULT
  dataset_id: HPONeuro
  metric: micro-f1
  dataset_slice_type: random
  num_classes: 10
  global_channels: 64
  global_channel_type: Pretrained
  include_obs_x_in_pooling: False
  is_obs_sequential: False
  lr: 0.001

  batch_size: 8
  eval_batch_size: 3
  accumulate_grad_batches: 8
  data_sampler_num_workers: 30
  epochs: 200
  val_interval: 5
  log_dir: ../lightning_logs_neuro/


SGI-HPONeuro-BASE: &SGI-HPONeuro-BASE
  <<: *HPONeuro
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

SGI-HPONeuro-Linear: &SGI-HPONeuro-Linear
  <<: *SGI-HPONeuro-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

SGI-HPONeuro-Linear-SHORT: &SGI-HPONeuro-Linear-SHORT
  <<: *SGI-HPONeuro-Linear
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 1.9119e-7

SGI-HPONeuro-Linear-TRAIN-MAX-EVAL-SHORT: &SGI-HPONeuro-Linear-TRAIN-MAX-EVAL-SHORT
  <<: *SGI-HPONeuro-Linear
  train_dataset_slice_range_1: 55
  train_dataset_slice_range_2: 56
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000098108

SGI-HPONeuro-SAGE: &SGI-HPONeuro-SAGE
  <<: *SGI-HPONeuro-BASE
  gnn_name: SAGEConv
  readout_name: mean
  lambda_l2: 1e-3

SGI-HPONeuro-GCN-SHORT:
  <<: *SGI-HPONeuro-SAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 1.9873e-7

SGI-HPONeuro-SAGE-SHORT: &SGI-HPONeuro-SAGE-SHORT
  <<: *SGI-HPONeuro-SAGE
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000012889

SGI-HPONeuro-SAGE-25P: &SGI-HPONeuro-SAGE-25P
  <<: *SGI-HPONeuro-SAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2
  lambda_l2: 4.1256e-7

SGI-HPONeuro-SAGE-50P: &SGI-HPONeuro-SAGE-50P
  <<: *SGI-HPONeuro-SAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2
  lambda_l2: 1.8303e-7

SGI-HPONeuro-SAGE-MAX: &SGI-HPONeuro-SAGE-MAX
  <<: *SGI-HPONeuro-SAGE
  dataset_slice_range_1: 55
  dataset_slice_range_2: 56
  lambda_l2: 0.0000049517

SGI-HPONeuro-SAGE-TRAIN-MAX-EVAL-SHORT:
  <<: *SGI-HPONeuro-SAGE
  train_dataset_slice_range_1: 55
  train_dataset_slice_range_2: 56
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.00014745


SGI-HPONeuro-E2D2F64: &SGI-HPONeuro-E2D2F64
  <<: *HPONeuro
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  gnn_name: SAGEConv
  use_decoder: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.95
  data_sampler_no_drop_pos_edges: False
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 300  # todo

SGI-HPONeuro-E2D2F64-X:
  <<: *SGI-HPONeuro-E2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

SGI-HPONeuro-E2D2F64-ISI: &SGI-HPONeuro-E2D2F64-ISI
  <<: *SGI-HPONeuro-E2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.95
  data_sampler_no_drop_pos_edges: False

SGI-HPONeuro-E2D2F64-ISI-X: &SGI-HPONeuro-E2D2F64-ISI-X
  <<: *SGI-HPONeuro-E2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

SGI-HPONeuro-E2D2F64-ISI-X-GB:
  <<: *SGI-HPONeuro-E2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.01



HPOMetab: &HPOMetab
  <<: *DEFAULT
  dataset_id: HPOMetab
  dataset_slice_type: random
  num_classes: 6
  global_channels: 64
  global_channel_type: Pretrained
  include_obs_x_in_pooling: False
  is_obs_sequential: False
  lr: 0.001

  batch_size: 8
  eval_batch_size: 3
  accumulate_grad_batches: 8
  data_sampler_num_workers: 30
  epochs: 200
  val_interval: 5
  log_dir: ../lightning_logs_metab/


SGI-HPOMetab-BASE: &SGI-HPOMetab-BASE
  <<: *HPOMetab
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

SGI-HPOMetab-Linear: &SGI-HPOMetab-Linear
  <<: *SGI-HPOMetab-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

SGI-HPOMetab-Linear-SHORT: &SGI-HPOMetab-Linear-SHORT
  <<: *SGI-HPOMetab-Linear
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000055036

SGI-HPOMetab-Linear-TRAIN-MAX-EVAL-SHORT: &SGI-HPOMetab-Linear-TRAIN-MAX-EVAL-SHORT
  <<: *SGI-HPOMetab-Linear
  train_dataset_slice_range_1: 50
  train_dataset_slice_range_2: 51
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.0000031107


SGI-HPOMetab-SAGE: &SGI-HPOMetab-SAGE
  <<: *SGI-HPOMetab-BASE
  gnn_name: SAGEConv
  readout_name: mean
  lambda_l2: 1e-3

SGI-HPOMetab-GCN-SHORT:
  <<: *SGI-HPOMetab-SAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.00044598

SGI-HPOMetab-SAGE-SHORT: &SGI-HPOMetab-SAGE-SHORT
  <<: *SGI-HPOMetab-SAGE
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000028790

SGI-HPOMetab-SAGE-25P: &SGI-HPOMetab-SAGE-25P
  <<: *SGI-HPOMetab-SAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2
  lambda_l2: 0.00039314

SGI-HPOMetab-SAGE-50P: &SGI-HPOMetab-SAGE-50P
  <<: *SGI-HPOMetab-SAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2
  lambda_l2: 0.00048598

SGI-HPOMetab-SAGE-MAX: &SGI-HPOMetab-SAGE-MAX
  <<: *SGI-HPOMetab-SAGE
  dataset_slice_range_1: 50
  dataset_slice_range_2: 51
  lambda_l2: 0.0000017804

SGI-HPOMetab-SAGE-TRAIN-MAX-EVAL-SHORT:
  <<: *SGI-HPOMetab-SAGE
  train_dataset_slice_range_1: 50
  train_dataset_slice_range_2: 51
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000019960


SGI-HPOMetab-E2D2F64: &SGI-HPOMetab-E2D2F64
  <<: *HPOMetab
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  gnn_name: SAGEConv
  use_decoder: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.95
  data_sampler_no_drop_pos_edges: False
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 300  # todo

SGI-HPOMetab-E2D2F64-X:
  <<: *SGI-HPOMetab-E2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

SGI-HPOMetab-E2D2F64-ISI: &SGI-HPOMetab-E2D2F64-ISI
  <<: *SGI-HPOMetab-E2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.95
  data_sampler_no_drop_pos_edges: False

SGI-HPOMetab-E2D2F64-ISI-X: &SGI-HPOMetab-E2D2F64-ISI-X
  <<: *SGI-HPOMetab-E2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

SGI-HPOMetab-E2D2F64-ISI-X-GB:
  <<: *SGI-HPOMetab-E2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.01


EMUser: &EMUser
  <<: *DEFAULT
  dataset_id: EMUser
  dataset_slice_type: random
  num_classes: 2
  global_channels: 64
  global_channel_type: Pretrained
  is_obs_sequential: False
  lr: 0.001

  batch_size: 64
  eval_batch_size: 3
  accumulate_grad_batches: 1
  data_sampler_num_workers: 20
  epochs: 200
  val_interval: 5
  log_dir: ../lightning_logs_emuser_report/


SGI-EMUser-BASE: &SGI-EMUser-BASE
  <<: *EMUser
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

SGI-EMUser-Linear: &SGI-EMUser-Linear
  <<: *SGI-EMUser-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

SGI-EMUser-Linear-SHORT: &SGI-EMUser-Linear-SHORT
  <<: *SGI-EMUser-Linear
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  lambda_l2: 0.0000014086

SGI-EMUser-Linear-TRAIN-MAX-EVAL-SHORT: &SGI-EMUser-Linear-TRAIN-MAX-EVAL-SHORT
  <<: *SGI-EMUser-Linear
  train_dataset_slice_range_1: 499
  train_dataset_slice_range_2: 500
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  lambda_l2: 0.00010494


SGI-EMUser-SAGE: &SGI-EMUser-SAGE
  <<: *SGI-EMUser-BASE
  gnn_name: SAGEConv
  readout_name: mean
  lambda_l2: 1e-3

SGI-EMUser-GCN-SHORT:
  <<: *SGI-EMUser-SAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11

SGI-EMUser-SAGE-SHORT: &SGI-EMUser-SAGE-SHORT
  <<: *SGI-EMUser-SAGE
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  lambda_l2: 0.00019239

SGI-EMUser-SAGE-25P: &SGI-EMUser-SAGE-25P
  <<: *SGI-EMUser-SAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2
  lambda_l2: 0.00023945

SGI-EMUser-SAGE-50P: &SGI-EMUser-SAGE-50P
  <<: *SGI-EMUser-SAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2
  lambda_l2: 0.0000070983

SGI-EMUser-SAGE-MAX: &SGI-EMUser-SAGE-MAX
  <<: *SGI-EMUser-SAGE
  dataset_slice_range_1: 499
  dataset_slice_range_2: 500
  lambda_l2: 0.000039415

SGI-EMUser-SAGE-TRAIN-MAX-EVAL-SHORT:
  <<: *SGI-EMUser-SAGE
  train_dataset_slice_range_1: 499
  train_dataset_slice_range_2: 500
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  lambda_l2: 0.00024352


SGI-EMUser-E2D2F64: &SGI-EMUser-E2D2F64
  <<: *EMUser
  dataset_slice_range_1: 6
  dataset_slice_range_2: 11
  gnn_name: SAGEConv
  use_decoder: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.5
  data_sampler_no_drop_pos_edges: False  # todo
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 400  # todo

SGI-EMUser-E2D2F64-X:
  <<: *SGI-EMUser-E2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

SGI-EMUser-E2D2F64-ISI: &SGI-EMUser-E2D2F64-ISI
  <<: *SGI-EMUser-E2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.5
  data_sampler_no_drop_pos_edges: False  # todo

SGI-EMUser-E2D2F64-ISI-X: &SGI-EMUser-E2D2F64-ISI-X
  <<: *SGI-EMUser-E2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

SGI-EMUser-E2D2F64-ISI-X-GB:
  <<: *SGI-EMUser-E2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.01
