DEFAULT: &DEFAULT
  use_gpu: True  # todo
  gpu_ids: [1]
  num_gpus_total: 4
  num_gpus_to_use: 1
  model_debug: False
  dataset_debug: False
  dataset_seed: 42
  model_seed: 42
  verbose: 1
  save_model: True
  val_interval: 1
  data_sampler_num_workers: 5  # todo
  precision: 16
  accumulate_grad_batches: 16  # todo
  use_pruner: False

  lr: 0.001
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 75
  use_skip: True


FNTN: &FNTN
  <<: *DEFAULT
  dataset_id: "0.0"
  dataset_slice_type: num_edges
  num_classes: 4
  global_channels: 32
  global_channel_type: Embedding
  obs_max_len: 20
  log_dir: ../lightning_logs_fntn/

DNS-FNTN-TEST:
  <<: *FNTN
  save_model: True
  model_debug: False
  dataset_debug: True
  lambda_aux_x: 1.0
  lambda_aux_e: 1.0
  epochs: 2

DNS-FNTN-BASE: &DNS-FNTN-BASE
  <<: *FNTN
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

DNS-FNTN-Linear: &DNS-FNTN-Linear
  <<: *DNS-FNTN-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

DNS-FNTN-Linear-SHORT: &DNS-FNTN-Linear-SHORT
  <<: *DNS-FNTN-Linear
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

DNS-FNTN-Linear-SHORT-PGA:
  <<: *DNS-FNTN-Linear-SHORT
  use_pergraph_attr: True
  lambda_l2: 4.5200e-7

DNS-FNTN-BISAGE: &DNS-FNTN-BISAGE
  <<: *DNS-FNTN-BASE
  gnn_name: SAGEConv
  is_bidirectional: True
  readout_name: mean
  lambda_l2: 1e-3

DNS-FNTN-BIGCN-SHORT: &DNS-FNTN-BIGCN-SHORT
  <<: *DNS-FNTN-BISAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10
  lambda_l2: 0.00043154

DNS-FNTN-BISAGE-SHORT: &DNS-FNTN-BISAGE-SHORT
  <<: *DNS-FNTN-BISAGE
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

DNS-FNTN-BISAGE-LONG: &DNS-FNTN-BISAGE-LONG
  <<: *DNS-FNTN-BISAGE
  dataset_slice_range_1: 100
  dataset_slice_range_2: 105

DNS-FNTN-BISAGE-XLONG: &DNS-FNTN-BISAGE-XLONG
  <<: *DNS-FNTN-BISAGE
  dataset_slice_range_1: 200
  dataset_slice_range_2: 205

DNS-FNTN-BISAGE-25P: &DNS-FNTN-BISAGE-25P
  <<: *DNS-FNTN-BISAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2

DNS-FNTN-BISAGE-50P: &DNS-FNTN-BISAGE-50P
  <<: *DNS-FNTN-BISAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2

DNS-FNTN-BISAGE-MAX: &DNS-FNTN-BISAGE-MAX
  <<: *DNS-FNTN-BISAGE
  dataset_slice_range_1: 3089
  dataset_slice_range_2: 3090

DNS-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT: &DNS-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT
  <<: *DNS-FNTN-BISAGE
  train_dataset_slice_range_1: 3089
  train_dataset_slice_range_2: 3090
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

DNS-FNTN-BISAGE-SHORT-0SG: &DNS-FNTN-BISAGE-SHORT-0SG
  <<: *DNS-FNTN-BISAGE-SHORT
  data_use_obs_edge_only: False

DNS-FNTN-BISAGE-LONG-0SG: &DNS-FNTN-BISAGE-LONG-0SG
  <<: *DNS-FNTN-BISAGE-LONG
  data_use_obs_edge_only: False

DNS-FNTN-BISAGE-XLONG-0SG: &DNS-FNTN-BISAGE-XLONG-0SG
  <<: *DNS-FNTN-BISAGE-XLONG
  data_use_obs_edge_only: False

DNS-FNTN-BISAGE-MAX-0SG: &DNS-FNTN-BISAGE-MAX-0SG
  <<: *DNS-FNTN-BISAGE-MAX
  data_use_obs_edge_only: False

DNS-FNTN-BISAGE-SHORT-1SG: &DNS-FNTN-BISAGE-SHORT-1SG
  <<: *DNS-FNTN-BISAGE-SHORT
  data_use_obs_edge_only: False
  data_sampler_num_hops: 1

DNS-FNTN-BIGCN-SHORT-PGA:
  <<: *DNS-FNTN-BIGCN-SHORT
  use_pergraph_attr: True

DNS-FNTN-BISAGE-SHORT-PGA:
  <<: *DNS-FNTN-BISAGE-SHORT
  use_pergraph_attr: True
  lambda_l2: 0.00028476

DNS-FNTN-BISAGE-LONG-PGA:
  <<: *DNS-FNTN-BISAGE-LONG
  use_pergraph_attr: True
  lambda_l2: 0.00023504

DNS-FNTN-BISAGE-25P-PGA:
  <<: *DNS-FNTN-BISAGE-25P
  use_pergraph_attr: True
  lambda_l2: 0.00026687

DNS-FNTN-BISAGE-50P-PGA:
  <<: *DNS-FNTN-BISAGE-50P
  use_pergraph_attr: True
  lambda_l2: 0.00026903

DNS-FNTN-BISAGE-XLONG-PGA:
  <<: *DNS-FNTN-BISAGE-XLONG
  use_pergraph_attr: True
  lambda_l2: 0.00018054

DNS-FNTN-BISAGE-MAX-PGA:
  <<: *DNS-FNTN-BISAGE-MAX
  use_pergraph_attr: True
  lambda_l2: 0.00022044

DNS-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT-PGA:
  <<: *DNS-FNTN-BISAGE-TRAIN-MAX-EVAL-SHORT
  use_pergraph_attr: True
  # lambda_l2: 0.00031851
  lambda_l2: 0.00049707

DNS-FNTN-BISAGE-SHORT-0SG-PGA:
  <<: *DNS-FNTN-BISAGE-SHORT-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000010522

DNS-FNTN-BISAGE-LONG-0SG-PGA:
  <<: *DNS-FNTN-BISAGE-LONG-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000043985

DNS-FNTN-BISAGE-XLONG-0SG-PGA:
  <<: *DNS-FNTN-BISAGE-XLONG-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000027055

DNS-FNTN-BISAGE-MAX-0SG-PGA:
  <<: *DNS-FNTN-BISAGE-MAX-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000056615

DNS-FNTN-BISAGE-SHORT-1SG-PGA:
  <<: *DNS-FNTN-BISAGE-SHORT-1SG
  use_pergraph_attr: True
  lambda_l2: 0.000347723


DNS-FNTN-BIE2D2F64: &DNS-FNTN-BIE2D2F64
  <<: *FNTN
  gnn_name: SAGEConv
  use_decoder: True
  is_bidirectional: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.5
  num_encoder_layers: 2
  num_decoder_body_layers: 2

DNS-FNTN-BIE2D2F64-X: &DNS-FNTN-BIE2D2F64-X  # not-used
  <<: *DNS-FNTN-BIE2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

DNS-FNTN-BIE2D2F64-X-PGA:
  <<: *DNS-FNTN-BIE2D2F64-X
  use_pergraph_attr: True
  lambda_aux_isi: 0.0
  lambda_l2: 0.00024979
  lambda_aux_x: 2.49
  data_sampler_dropout_edges: 0.55
  pool_ratio: 0.0016009

DNS-FNTN-BIE2D2F64-E:  # not-used
  <<: *DNS-FNTN-BIE2D2F64
  main_decoder_type: edge
  use_node_decoder: False
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_e: 0.5
  pool_ratio: 0.2

DNS-FNTN-BIE2D2F64-XE:  # not-used
  <<: *DNS-FNTN-BIE2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_x: 0.05
  lambda_aux_e: 0.1
  pool_ratio: 0.1

DNS-FNTN-BIE2D2F64-EX:  # not-used
  <<: *DNS-FNTN-BIE2D2F64
  main_decoder_type: edge
  use_node_decoder: True
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_e: 0.25
  pool_ratio: 0.1


DNS-FNTN-BIE2D2F64-ISI: &DNS-FNTN-BIE2D2F64-ISI
  <<: *DNS-FNTN-BIE2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.3

DNS-FNTN-BIE2D2F64-ISI-X: &DNS-FNTN-BIE2D2F64-ISI-X
  <<: *DNS-FNTN-BIE2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

DNS-FNTN-BIE2D2F64-ISI-X-GB:  # not-used
  <<: *DNS-FNTN-BIE2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.1

DNS-FNTN-BIE2D2F64-ISI-X-GB-PGA:
  <<: *DNS-FNTN-BIE2D2F64-ISI-X
  use_pergraph_attr: True
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 0.0018817
  lambda_aux_x: 5.80
  lambda_aux_isi: 1.85
  data_sampler_dropout_edges: 0.60
  pool_ratio: 0.010994



HPONeuro: &HPONeuro
  <<: *DEFAULT
  dataset_id: HPONeuro
  metric: micro-f1
  dataset_slice_type: random
  num_classes: 10
  global_channels: 64
  global_channel_type: Pretrained
  is_obs_sequential: False
  lr: 0.001

  batch_size: 64
  eval_batch_size: 3
  accumulate_grad_batches: 1
  data_sampler_num_workers: 20
  epochs: 200
  val_interval: 5
  log_dir: ../lightning_logs_neuro/


DNS-HPONeuro-BASE: &DNS-HPONeuro-BASE
  <<: *HPONeuro
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

DNS-HPONeuro-Linear: &DNS-HPONeuro-Linear
  <<: *DNS-HPONeuro-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

DNS-HPONeuro-Linear-SHORT: &DNS-HPONeuro-Linear-SHORT
  <<: *DNS-HPONeuro-Linear
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 1.9119e-7

DNS-HPONeuro-SAGE: &DNS-HPONeuro-SAGE
  <<: *DNS-HPONeuro-BASE
  gnn_name: SAGEConv
  readout_name: mean
  lambda_l2: 1e-3

DNS-HPONeuro-GCN-SHORT:
  <<: *DNS-HPONeuro-SAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 1.9873e-7

DNS-HPONeuro-SAGE-SHORT: &DNS-HPONeuro-SAGE-SHORT
  <<: *DNS-HPONeuro-SAGE
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000012889

DNS-HPONeuro-SAGE-25P: &DNS-HPONeuro-SAGE-25P
  <<: *DNS-HPONeuro-SAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2
  lambda_l2: 4.1256e-7

DNS-HPONeuro-SAGE-50P: &DNS-HPONeuro-SAGE-50P
  <<: *DNS-HPONeuro-SAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2
  lambda_l2: 1.8303e-7

DNS-HPONeuro-SAGE-MAX: &DNS-HPONeuro-SAGE-MAX
  <<: *DNS-HPONeuro-SAGE
  dataset_slice_range_1: 55
  dataset_slice_range_2: 56
  lambda_l2: 0.0000049517

DNS-HPONeuro-SAGE-TRAIN-MAX-EVAL-SHORT:
  <<: *DNS-HPONeuro-SAGE
  train_dataset_slice_range_1: 55
  train_dataset_slice_range_2: 56
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.00014745


DNS-HPONeuro-E2D2F64: &DNS-HPONeuro-E2D2F64
  <<: *HPONeuro
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  gnn_name: SAGEConv
  use_decoder: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.95
  data_sampler_no_drop_pos_edges: True
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 250  # todo

DNS-HPONeuro-E2D2F64-X:
  <<: *DNS-HPONeuro-E2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

DNS-HPONeuro-E2D2F64-ISI: &DNS-HPONeuro-E2D2F64-ISI
  <<: *DNS-HPONeuro-E2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.95
  data_sampler_no_drop_pos_edges: True

DNS-HPONeuro-E2D2F64-ISI-X: &DNS-HPONeuro-E2D2F64-ISI-X
  <<: *DNS-HPONeuro-E2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

DNS-HPONeuro-E2D2F64-ISI-X-GB:
  <<: *DNS-HPONeuro-E2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.01



HPOMetab: &HPOMetab
  <<: *DEFAULT
  dataset_id: HPOMetab
  dataset_slice_type: random
  num_classes: 6
  global_channels: 64
  global_channel_type: Pretrained
  is_obs_sequential: False
  lr: 0.001

  batch_size: 64
  eval_batch_size: 3
  accumulate_grad_batches: 1
  data_sampler_num_workers: 20
  epochs: 200
  val_interval: 5
  log_dir: ../lightning_logs_metab/


DNS-HPOMetab-BASE: &DNS-HPOMetab-BASE
  <<: *HPOMetab
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

DNS-HPOMetab-Linear: &DNS-HPOMetab-Linear
  <<: *DNS-HPOMetab-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

DNS-HPOMetab-Linear-SHORT: &DNS-HPOMetab-Linear-SHORT
  <<: *DNS-HPOMetab-Linear
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000055036


DNS-HPOMetab-SAGE: &DNS-HPOMetab-SAGE
  <<: *DNS-HPOMetab-BASE
  gnn_name: SAGEConv
  readout_name: mean
  lambda_l2: 1e-3

DNS-HPOMetab-GCN-SHORT:
  <<: *DNS-HPOMetab-SAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.00044598

DNS-HPOMetab-SAGE-SHORT: &DNS-HPOMetab-SAGE-SHORT
  <<: *DNS-HPOMetab-SAGE
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000028790

DNS-HPOMetab-SAGE-25P: &DNS-HPOMetab-SAGE-25P
  <<: *DNS-HPOMetab-SAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2
  lambda_l2: 0.00039314

DNS-HPOMetab-SAGE-50P: &DNS-HPOMetab-SAGE-50P
  <<: *DNS-HPOMetab-SAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2
  lambda_l2: 0.00048598

DNS-HPOMetab-SAGE-MAX: &DNS-HPOMetab-SAGE-MAX
  <<: *DNS-HPOMetab-SAGE
  dataset_slice_range_1: 50
  dataset_slice_range_2: 51
  lambda_l2: 0.0000017804

DNS-HPOMetab-SAGE-TRAIN-MAX-EVAL-SHORT:
  <<: *DNS-HPOMetab-SAGE
  train_dataset_slice_range_1: 50
  train_dataset_slice_range_2: 51
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  lambda_l2: 0.000019960


DNS-HPOMetab-E2D2F64: &DNS-HPOMetab-E2D2F64
  <<: *HPOMetab
  dataset_slice_range_1: 2
  dataset_slice_range_2: 7
  gnn_name: SAGEConv
  use_decoder: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.95
  data_sampler_no_drop_pos_edges: True
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 250  # todo

DNS-HPOMetab-E2D2F64-X:
  <<: *DNS-HPOMetab-E2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

DNS-HPOMetab-E2D2F64-ISI: &DNS-HPOMetab-E2D2F64-ISI
  <<: *DNS-HPOMetab-E2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.95
  data_sampler_no_drop_pos_edges: True

DNS-HPOMetab-E2D2F64-ISI-X: &DNS-HPOMetab-E2D2F64-ISI-X
  <<: *DNS-HPOMetab-E2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

DNS-HPOMetab-E2D2F64-ISI-X-GB:
  <<: *DNS-HPOMetab-E2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.01


CCAMiner: &CCAMiner
  <<: *DEFAULT
  dataset_id: "y1"
  dataset_slice_type: num_edges
  num_classes: 5
  global_channels: 32
  global_channel_type: Embedding
  obs_max_len: 14

  batch_size: 16  # todo
  eval_batch_size: 32  # todo
  accumulate_grad_batches: 1
  data_sampler_num_workers: 4  # todo
  lr: 0.001
  epochs: 500  # todo
  log_dir: ../lightning_logs_ccaminer/

DNS-CCAMiner-BASE: &DNS-CCAMiner-BASE
  <<: *CCAMiner
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

DNS-CCAMiner-Linear: &DNS-CCAMiner-Linear
  <<: *DNS-CCAMiner-BASE
  gnn_name: Linear
  readout_name: sum
  lambda_l2: 1e-3

DNS-CCAMiner-Linear-SHORT: &DNS-CCAMiner-Linear-SHORT
  <<: *DNS-CCAMiner-Linear
  dataset_slice_range_1: 1
  dataset_slice_range_2: 6


DNS-CCAMiner-BISAGE: &DNS-CCAMiner-BISAGE
  <<: *DNS-CCAMiner-BASE
  gnn_name: SAGEConv
  is_bidirectional: True
  readout_name: sum
  lambda_l2: 1e-3

DNS-CCAMiner-BIGCN-SHORT:
  <<: *DNS-CCAMiner-BISAGE
  gnn_name: GCNConv
  dataset_slice_range_1: 1
  dataset_slice_range_2: 6

DNS-CCAMiner-BISAGE-SHORT: &DNS-CCAMiner-BISAGE-SHORT
  <<: *DNS-CCAMiner-BISAGE
  dataset_slice_range_1: 1
  dataset_slice_range_2: 6

DNS-CCAMiner-BISAGE-25P: &DNS-CCAMiner-BISAGE-25P
  <<: *DNS-CCAMiner-BISAGE
  dataset_slice_ratio: 0.25
  dataset_slice_range_2: 2

DNS-CCAMiner-BISAGE-50P: &DNS-CCAMiner-BISAGE-50P
  <<: *DNS-CCAMiner-BISAGE
  dataset_slice_ratio: 0.5
  dataset_slice_range_2: 2

DNS-CCAMiner-BISAGE-MAX: &DNS-CCAMiner-BISAGE-MAX
  <<: *DNS-CCAMiner-BISAGE
  dataset_slice_range_1: 120
  dataset_slice_range_2: 121

DNS-CCAMiner-BISAGE-TRAIN-MAX-EVAL-SHORT:
  <<: *DNS-CCAMiner-BISAGE
  train_dataset_slice_range_1: 120
  train_dataset_slice_range_2: 121
  dataset_slice_range_1: 1
  dataset_slice_range_2: 6


DNS-CCAMiner-BIE2D2F64: &DNS-CCAMiner-BIE2D2F64
  <<: *CCAMiner
  dataset_slice_range_1: 1
  dataset_slice_range_2: 6
  gnn_name: SAGEConv
  use_decoder: True
  is_bidirectional: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.5
  num_encoder_layers: 2
  num_decoder_body_layers: 2

DNS-CCAMiner-BIE2D2F64-X:
  <<: *DNS-CCAMiner-BIE2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

DNS-CCAMiner-BIE2D2F64-ISI: &DNS-CCAMiner-BIE2D2F64-ISI
  <<: *DNS-CCAMiner-BIE2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.3

DNS-CCAMiner-BIE2D2F64-ISI-X: &DNS-CCAMiner-BIE2D2F64-ISI-X
  <<: *DNS-CCAMiner-BIE2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

DNS-CCAMiner-BIE2D2F64-ISI-X-GB:
  <<: *DNS-CCAMiner-BIE2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.01
