DEFAULT: &DEFAULT
  use_gpu: True  # todo
  gpu_ids: [0]
  num_gpus_total: 4
  num_gpus_to_use: 1
  model_debug: False
  dataset_debug: False
  dataset_seed: 42
  model_seed: 42
  verbose: 1
  save_model: True
  val_interval: 1
  data_sampler_num_workers: 5  # todo
  precision: 16
  accumulate_grad_batches: 16  # todo
  use_pruner: False

  lr: 0.001
  num_encoder_layers: 2
  num_decoder_body_layers: 2
  epochs: 75
  use_skip: True


FNTN: &FNTN
  <<: *DEFAULT
  dataset_id: "0.0"
  dataset_slice_type: num_edges
  num_classes: 4
  global_channels: 32
  global_channel_type: Embedding
  obs_max_len: 20

DNS-FNTN-TEST:
  <<: *FNTN
  save_model: True
  model_debug: False
  dataset_debug: True
  lambda_aux_x: 1.0
  lambda_aux_e: 1.0
  epochs: 2

DNS-FNTN-BASE: &DNS-FNTN-BASE
  <<: *FNTN
  use_node_decoder: False
  use_edge_decoder: False
  data_sampler_num_hops: 0
  data_sampler_neg_sample_ratio: 0.0
  data_sampler_dropout_edges: 0.0
  data_use_obs_edge_only: True
  use_decoder: False

DNS-FNTN-Linear: &DNS-FNTN-Linear
  <<: *DNS-FNTN-BASE
  gnn_name: Linear
  readout_name: mean
  lambda_l2: 1e-3

DNS-FNTN-Linear-SHORT: &DNS-FNTN-Linear-SHORT
  <<: *DNS-FNTN-Linear
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

DNS-FNTN-Linear-LONG: &DNS-FNTN-Linear-LONG
  <<: *DNS-FNTN-Linear
  dataset_slice_range_1: 100
  dataset_slice_range_2: 105

DNS-FNTN-Linear-XLONG: &DNS-FNTN-Linear-XLONG
  <<: *DNS-FNTN-Linear
  dataset_slice_range_1: 200
  dataset_slice_range_2: 205

DNS-FNTN-Linear-MAX: &DNS-FNTN-Linear-MAX
  <<: *DNS-FNTN-Linear
  dataset_slice_range_1: 3089
  dataset_slice_range_2: 3090


DNS-FNTN-BISAGE: &DNS-FNTN-BISAGE
  <<: *DNS-FNTN-BASE
  gnn_name: SAGEConv
  is_bidirectional: True
  readout_name: mean
  lambda_l2: 1e-3

DNS-FNTN-BISAGE-SHORT: &DNS-FNTN-BISAGE-SHORT
  <<: *DNS-FNTN-BISAGE
  dataset_slice_range_1: 5
  dataset_slice_range_2: 10

DNS-FNTN-BISAGE-LONG: &DNS-FNTN-BISAGE-LONG
  <<: *DNS-FNTN-BISAGE
  dataset_slice_range_1: 100
  dataset_slice_range_2: 105

DNS-FNTN-BISAGE-XLONG: &DNS-FNTN-BISAGE-XLONG
  <<: *DNS-FNTN-BISAGE
  dataset_slice_range_1: 200
  dataset_slice_range_2: 205

DNS-FNTN-BISAGE-MAX: &DNS-FNTN-BISAGE-MAX
  <<: *DNS-FNTN-BISAGE
  dataset_slice_range_1: 3089
  dataset_slice_range_2: 3090

DNS-FNTN-BISAGE-SHORT-0SG: &DNS-FNTN-BISAGE-SHORT-0SG
  <<: *DNS-FNTN-BISAGE-SHORT
  data_use_obs_edge_only: False

DNS-FNTN-BISAGE-LONG-0SG: &DNS-FNTN-BISAGE-LONG-0SG
  <<: *DNS-FNTN-BISAGE-LONG
  data_use_obs_edge_only: False

DNS-FNTN-BISAGE-XLONG-0SG: &DNS-FNTN-BISAGE-XLONG-0SG
  <<: *DNS-FNTN-BISAGE-XLONG
  data_use_obs_edge_only: False

DNS-FNTN-BISAGE-MAX-0SG: &DNS-FNTN-BISAGE-MAX-0SG
  <<: *DNS-FNTN-BISAGE-MAX
  data_use_obs_edge_only: False

DNS-FNTN-BISAGE-SHORT-1SG: &DNS-FNTN-BISAGE-SHORT-1SG
  <<: *DNS-FNTN-BISAGE-SHORT
  data_use_obs_edge_only: False
  data_sampler_num_hops: 1

DNS-FNTN-BISAGE-SHORT-PGA:
  <<: *DNS-FNTN-BISAGE-SHORT
  use_pergraph_attr: True
  lambda_l2: 0.00022681

DNS-FNTN-BISAGE-LONG-PGA:
  <<: *DNS-FNTN-BISAGE-LONG
  use_pergraph_attr: True
  lambda_l2: 0.00010766

DNS-FNTN-BISAGE-XLONG-PGA:
  <<: *DNS-FNTN-BISAGE-XLONG
  use_pergraph_attr: True
  lambda_l2: 0.000043635

DNS-FNTN-BISAGE-MAX-PGA:
  <<: *DNS-FNTN-BISAGE-MAX
  use_pergraph_attr: True
  lambda_l2: 0.00015872

DNS-FNTN-BISAGE-SHORT-0SG-PGA:
  <<: *DNS-FNTN-BISAGE-SHORT-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000010522

DNS-FNTN-BISAGE-LONG-0SG-PGA:
  <<: *DNS-FNTN-BISAGE-LONG-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000043985

DNS-FNTN-BISAGE-XLONG-0SG-PGA:
  <<: *DNS-FNTN-BISAGE-XLONG-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000027055

DNS-FNTN-BISAGE-MAX-0SG-PGA:
  <<: *DNS-FNTN-BISAGE-MAX-0SG
  use_pergraph_attr: True
  lambda_l2: 0.000056615

DNS-FNTN-BISAGE-SHORT-1SG-PGA:
  <<: *DNS-FNTN-BISAGE-SHORT-1SG
  use_pergraph_attr: True
  lambda_l2: 0.000347723


DNS-FNTN-BIE2D2F64: &DNS-FNTN-BIE2D2F64
  <<: *FNTN
  gnn_name: SAGEConv
  use_decoder: True
  is_bidirectional: True
  data_sampler_num_hops: 1
  data_sampler_neg_sample_ratio: 1.0
  data_sampler_dropout_edges: 0.5
  num_encoder_layers: 2
  num_decoder_body_layers: 2

DNS-FNTN-BIE2D2F64-X: &DNS-FNTN-BIE2D2F64-X  # not-used
  <<: *DNS-FNTN-BIE2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  pool_ratio: 0.1

DNS-FNTN-BIE2D2F64-X-PGA:
  <<: *DNS-FNTN-BIE2D2F64-X
  use_pergraph_attr: True
  lambda_l2: 0.0046803
  lambda_aux_x: 0.06
  lambda_aux_isi: 0.0
  data_sampler_dropout_edges: 0.4
  pool_ratio: 0.070401

DNS-FNTN-BIE2D2F64-E:  # not-used
  <<: *DNS-FNTN-BIE2D2F64
  main_decoder_type: edge
  use_node_decoder: False
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_e: 0.5
  pool_ratio: 0.2

DNS-FNTN-BIE2D2F64-XE:  # not-used
  <<: *DNS-FNTN-BIE2D2F64
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_x: 0.05
  lambda_aux_e: 0.1
  pool_ratio: 0.1

DNS-FNTN-BIE2D2F64-EX:  # not-used
  <<: *DNS-FNTN-BIE2D2F64
  main_decoder_type: edge
  use_node_decoder: True
  use_edge_decoder: True
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_e: 0.25
  pool_ratio: 0.1


DNS-FNTN-BIE2D2F64-ISI: &DNS-FNTN-BIE2D2F64-ISI
  <<: *DNS-FNTN-BIE2D2F64
  use_inter_subgraph_infomax: True
  data_sampler_dropout_edges: 0.3

DNS-FNTN-BIE2D2F64-ISI-X: &DNS-FNTN-BIE2D2F64-ISI-X
  <<: *DNS-FNTN-BIE2D2F64-ISI
  main_decoder_type: node
  use_node_decoder: True
  use_edge_decoder: False

DNS-FNTN-BIE2D2F64-ISI-X-GB:  # not-used
  <<: *DNS-FNTN-BIE2D2F64-ISI-X
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 1e-3
  lambda_aux_x: 0.1
  lambda_aux_isi: 0.1
  pool_ratio: 0.1

DNS-FNTN-BIE2D2F64-ISI-X-GB-PGA:
  <<: *DNS-FNTN-BIE2D2F64-ISI-X
  use_pergraph_attr: True
  inter_subgraph_infomax_edge_type: global
  lambda_l2: 0.0018817
  lambda_aux_x: 5.80
  lambda_aux_isi: 1.85
  data_sampler_dropout_edges: 0.60
  pool_ratio: 0.010994
